### ISSUE TITLE
練習：@functionを作る

### ISSUE THREAD

**Issue by geckotang** [mamiline6/sass_practice#10]
以下の様なSCSSが、

``` scss
@mixin rem( $size) {
  font-size: rem($size);
  font-size: $size;
}

.block {
  @include rem(16px);
}
.block2 {
  @include rem(10px);
}
```

次のように出力されるように、`rem()`というsass functionを作成してください。

``` css
.block {
  font-size: 1.6rem;
  font-size: 16px;
}
.block2 {
  font-size: 1rem;
  font-size: 10px;
}
```

ちなみに、計算する際の基準となるフォントサイズは、10px（≒62.5%）です。
