### ISSUE TITLE
練習：placeholder selector（%）を使う

### ISSUE THREAD

**Issue by geckotang** [mamiline6/sass_practice#12]
例えば、共通部分をまとめるために、mixinを使用します。
その時、以下の様なSCSSを書いた場合、

``` scss
@mixin btn($border-color:#ccc) {
  display: inline-block;
  min-width: 100px;
  min-height: 40px;
  border: 1px solid $border-color;
  border-radius: 4px;
}
.btn-normal {
  @include btn();
  background-color: white;
}
.btn-primary {
  @include btn(skyblue);
  background-color: blue;
}
.btn-error {
  @include btn(tomato);
  background-color: red;
}
```

出力されるCSSでは以下のようになります。

``` css
.btn-normal {
  display: inline-block;
  min-width: 100px;
  min-height: 40px;
  border: 1px solid #ccc;
  border-radius: 4px;
  background-color: white;
}

.btn-primary {
  display: inline-block;
  min-width: 100px;
  min-height: 40px;
  border: 1px solid skyblue;
  border-radius: 4px;
  background-color: blue;
}

.btn-error {
  display: inline-block;
  min-width: 100px;
  min-height: 40px;
  border: 1px solid tomato;
  border-radius: 4px;
  background-color: red;
}
```

SCSS上では、ボタンのスタイルをまとめて管理できているので、特に問題はありません。ですが、CSS上は同じ記述が重複しています。もしSCSSを使わずに、CSSを書いた時、このようなCSSを書くでしょうか。多くの場合は、書かないでしょう。

そこで、Sassのextendを使って、以下の様なCSSが生成されるように頑張ってみましょう。

``` css
.btn-normal, .btn-primary, .btn-error {
  display: inline-block;
  min-width: 100px;
  min-height: 40px;
  border: 1px solid #ccc;
  border-radius: 4px;
}

.btn-normal {
  background-color: white;
}

.btn-primary {
  border-color: skyblue;
  background-color: blue;
}

.btn-error {
  border-color: tomato;
  background-color: red;
}
```
