### ISSUE TITLE
練習：共通部分をまとめる

### ISSUE THREAD

**Issue by geckotang** [mamiline6/sass_practice#3]
@mamiline6 

以下のような出力になるSCSSを書いて、PRsを作成してください。
PRsを作成したら、マージせずに、@geckotangに教えてください。

``` css
.icon-a {
  display: inline-block;
  width: 10px;
  height: 22px;
  background: url("img/icon-a.png") no-repeat top left;
}
.icon-b {
  display: inline-block;
  width: 12px;
  height: 16px;
  background: url("img/icon-b.png") no-repeat top left;
}
.icon-c {
  display: inline-block;
  width: 22px;
  height: 24px;
  background: url("img/icon-c.png") no-repeat top left;
}
```

ヒント：mixinやextendなどを使うことで、記述を楽にしたり、重複するようなコードを1箇所で管理することができます。

**Comment by geckotang** [comment]
@mamiline6 #6 見ました。mixinは使えてるし、大きな問題はないかなと思います。

他の方法としては

``` scss
@mixin iconBase ($width, $height, $icon-name) {
  display: inline-block;
  width: $width;
  height: $height;
  background: url("img/#{$icon-name}.png") top left no-repeat;
}
.icon-a {
  @include iconBase($width:10px, $height:22pc, $icon-name:icon-a);
}
.icon-b {
  @include iconBase($width:12px, $height:22px, $icon-name:icon-b);
}
.icon-c {
  @include iconBase($width:22px, $height:24px, $icon-name:icon-c);
}
```

`.icon-a`というセレクタと`icon-a.png`という画像のファイル名は、必ずしも対になるわけでもないので、 @mamiline6 のアイコンのファイル名をmixinの引数に渡すのは良い方法だと思います。

ただ、完全にセレクタとファイル名と一致させたい場合は以下の様な書き方をしてもいいかもしれません。

``` sass
@mixin iconBase ($width, $height, $icon-name) {
  display: inline-block;
  width: $width;
  height: $height;
  background: url("img/#{$icon-name}.png") top left no-repeat;
}

$iconNameList: (
  'icon-a': (10px, 22px),
  'icon-b': (12px, 22px),
  'icon-c': (22px, 24px),
);

@each $name, $size in $iconNameList {
  .#{$name} {
    @include iconBase($width: nth($size, 1), $height: nth($size, 2), $icon-name:$name);
  }
}
```

とはいえ、ぱっと見がわかりづらい（生成後のCSSが想像しづらい）ので、あまりおすすめしません。
