### ISSUE TITLE
練習：BEMのようなセレクタを簡単に書く

### ISSUE THREAD

**Issue by geckotang** [mamiline6/sass_practice#8]
@mamiline6 
&を使用して、以下の様なCSSが生成されるSCSSを作成してください。

``` css
.tabs {
  text-align: center;
  border-bottom: 1px solid #aaa;
}
.tabs__tab {
  display: inline-block;
  margin-bottom: -1px;
  padding: 5px 10px;
  border: 1px solid #aaa;
  border-radius: 4px 4px 0 0;
  color: #eee;
  background-color: #aaa;
}
.tabs__tab.is-active {
  color: #000;
  background-color: #fff;
  border-bottom-color: #fff;
}
.tabs__text {
  font-size: 14px;
}
```

あまり関係ありませんがHTMLと見た目は以下の様な感じです。

![image](https://cloud.githubusercontent.com/assets/683965/7990152/f1930302-0b29-11e5-9245-0a5ec314d317.png)

``` html

<div class="tabs">
  <div class="tabs__tab is-active">
    <div class="tabs__text">タブ1</div>
  </div>
  <div class="tabs__tab">
    <div class="tabs__text">タブ2</div>
  </div>
  <div class="tabs__tab">
    <div class="tabs__text">タブ3</div>
  </div>
</div>
```
